apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.2
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-password
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-user-db-configmap
              key: MARIADB_USER
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-user-db-configmap
              key: MARIADB_DATABASE
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: db-load-script-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-data
        emptyDir: {}
      - name: db-load-script-volume
        configMap:
          name: db-load-script-configmap
