apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: ristabel/ecom-web:v1
          ports:
            - containerPort: 80 
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root-password
                  key: MARIADB_ROOT_PASSWORD
            - name: DB_USER
              value: ecomuser 
            - name: DB_NAME
              value: ecomdb
            - name: FEATURE_DARK_MODE
              valueFrom:
                configMapKeyRef:
                  name: feature-toggle-config
                  key: FEATURE_DARK_MODE
      volumes:
        - name: db-load-script-volume
          configMap:
            name: db-load-script-configmap
