apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-mariadb
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  type: {{ .Values.db.type }}
