apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: {{ .Release.Name }}-{{ .Chart.Name }}-mariadb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
