apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: {{ .Release.Name }}-{{ .Chart.Name }}-mariadb-data-claim
spec:
    storageClassName: {{ .Values.pvc.class}}
    accessModes:
        - {{ .Values.pvc.access}}
    resources:
        requests:
            storage: {{ .Values.pvc.storage}}