apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-mariadb-root-password
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: ZWNvbXBhc3N3b3Jk  # Base64 encoded value of the root password 'ecompassword'
