apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-website-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-website
  ports:
    - protocol: {{ .Values.service.protocol }} 
      port: {{ .Values.service.port }}  
      targetPort:  {{ .Values.service.port }} 
  type: {{ .Values.service.type }}
